### ISSUE TITLE
License

### ISSUE THREAD

**Issue by dbirks** [StephLin/vscode-tmux-keybinding#1]
Hi, thank you very much for this extension. It's so simple but so helpful when you have that muscle memory for tmux. 

I'm looking to add it to NixOS (so I can define my vscode extensions [like this](https://github.com/dbirks/dotfiles/blob/53ca1e2419635250061cf372b9adcb096e6d6d44/nixos/etc/nixos/configuration.nix#L31-L43)), and it looks like most extensions there have a license. Would it be ok to add one?

Thanks again :+1:

**Comment by StephLin** [comment]
Dear @dbirks,

Thank you for your kind feedback! I will add a license for this extension soon.

**Comment by dbirks** [comment]
Ok awesome! Looking forward to the next release then, thanks again! :grin:
