### ISSUE TITLE
Split panes horizontally

### ISSUE THREAD

**Issue by redant777** [StephLin/vscode-tmux-keybinding#2]
In tmux to split a pane horizontally, the combination Ctrl+b and " (single quotation mark). I see this is not supported. Do you know if this ca be implemented?

**Comment by StephLin** [comment]
Hi @cristianburca,

Up to my understanding, the horizontal split is only effective (visually) when the location of the panel is on the left or right side, and the function is currently triggered via `ctrl+b %` (which is the command of vertical split).
One thing I can try is to distinguish the location of the panel and make the command more intuitive. How do you think?

Thanks a lot for your feedback!

**Comment by redant777** [comment]
Would be nice. Thanks!

**Comment by StephLin** [comment]
I implemented this feature and published in [vscode marketplace](https://marketplace.visualstudio.com/items?itemName=stephlin.vscode-tmux-keybinding) with version [0.0.7](https://github.com/StephLin/vscode-tmux-keybinding/tree/v0.0.7).
Please feel free to reopen it if you found any issue related to the horizontal split feature 😃.
