### ISSUE TITLE
Publish this VSCode extension also in open-vsx.org

### ISSUE THREAD

**Issue by elgalu** [StephLin/vscode-tmux-keybinding#3]
Would it be possible that you publish this VSCode extension also in https://open-vsx.org/

This would make it much easier to use the extension in project such as

* [gitpod.io](https://gitpod.io/)
* [theia-ide.org](https://theia-ide.org/)
* [VS Codium](https://vscodium.com/)
* [code-server](https://github.com/cdr/code-server)

thanks in advance

**Comment by StephLin** [comment]
Sounds great! I'll try it soon. 🙂

**Comment by StephLin** [comment]
This extension is published in Open VSX at https://open-vsx.org/extension/stephlin/vscode-tmux-keybinding. Cheers! 🍻
